# Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /server

# Install required packages
RUN apt-get update && apt-get install -y unixodbc-dev

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .


# Expose the port your application runs on
EXPOSE 3000

# Define the command to run your application
CMD ["node", "server.js"]
